package lib

import "main/types"

type Validation struct {
	ValidationID string
	Severity *types.Severity
	Description string
	Name string
}

var (
	ValidationIds = []string{
		"agency.agency_emai_validation",
		"agency.agency_fare_url_validation",
		"agency.agency_id_validation",
		"agency.agency_lang_validation",
		"agency.agency_phone_validation",
		"agency.agency_timezone_validation",
		"agency.agency_url_validation",
		"agency.parse_agency",
		"calendar.date_validation",
		"calendar.service_id_validation",
		"calendar_dates.date_validation",
		"calendar_dates.exception_type_validation",
		"calendar_dates.service_id_validation",
		"fare_attributes.agency_id_validation",
		"fare_attributes.currency_type_validation",
		"fare_attributes.fare_id_validation",
		"fare_attributes.payment_method_validation",
		"fare_attributes.price_validation",
		"fare_attributes.transfer_duration_validation",
		"fare_attributes.transfers_validation",
		"fare_rules.contains_id",
		"fare_rules.destination_id",
		"fare_rules.fare_id",
		"fare_rules.origin_id",
		"fare_rules.parse_fare_rule",
		"fare_rules.route_id",
		"feed_info.default_lang_validation",
		"feed_info.feed_contact_email_validation",
		"feed_info.feed_contact_url_validation",
		"feed_info.feed_end_date_validation",
		"feed_info.feed_lang_validation",
		"feed_info.feed_publisher_name_validation",
		"feed_info.feed_publisher_url_validation",
		"feed_info.feed_start_date_validation",
		"feed_info.feed_version_validation",
		"feed_info.parse_feed_info",
		"routes.agency_id_validation",
		"routes.continuous_drop_off_validation",
		"routes.continuous_pickup_validation",
		"routes.network_id_validation",
		"routes.parse_routes",
		"routes.route_color_validation",
		"routes.route_desc_validation",
		"routes.route_id_validation",
		"routes.route_long_name_validation",
		"routes.route_short_name_validation",
		"routes.route_sort_order_validation",
		"routes.route_text_color_validation",
		"routes.route_type_validation",
		"routes.route_url_validation",
		"shapes.parse_shapes",
		"shapes.shape_dist_traveled_validation",
		"shapes.shape_id_validation",
		"shapes.shape_pt_lat_validation",
		"shapes.shape_pt_lon_validation",
		"shapes.shape_pt_sequence_validation",
		"shapes.shape_sequence_validation",
		"stop_times.arrival_time_validation",
		"stop_times.continuous_drop_off_validation",
		"stop_times.continuous_pickup_validation",
		"stop_times.departure_time_validation",
		"stop_times.drop_off_booking_rule_id_validation",
		"stop_times.drop_off_type_validation",
		"stop_times.end_pickup_drop_off_window_validation",
		"stop_times.location_group_id_validation",
		"stop_times.parse_stop_times",
		"stop_times.pickup_booking_rule_id_validation",
		"stop_times.pickup_type_validation",
		"stop_times.shape_dist_traveled_validation",
		"stop_times.start_pickup_drop_off_window_validation",
		"stop_times.stop_headsign_validation",
		"stop_times.stop_id_validation",
		"stop_times.timepoint_validation",
		"stop_times.trip_id_validation",
		"stops.level_id_validation",
		"stops.location_type_validation",
		"stops.parent_station_validation",
		"stops.parse_stop",
		"stops.platform_code_validation",
		"stops.stop_code_validation",
		"stops.stop_desc_validation",
		"stops.stop_id_validation",
		"stops.stop_lat_validation",
		"stops.stop_lon_validation",
		"stops.stop_name_validation",
		"stops.stop_timezone_validation",
		"stops.tts_stop_name_validation",
		"stops.wheelchair_boarding_validation",
		"stops.zone_id_validation",
		"trips.bikes_allowed_validation",
		"trips.block_id_validation",
		"trips.direction_id_validation",
		"trips.parse_trips",
		"trips.pattern_id_group_validation",
		"trips.pattern_id_validation",
		"trips.route_id_validation",
		"trips.service_id_validation",
		"trips.shape_id_validation",
		"trips.stop_sequence_validation",
		"trips.trip_headsign_validation",
		"trips.trip_id_validation",
		"trips.trip_short_name_validation",
		"trips.wheelchair_accessible_validation",
	}
)