name: 'Build & Publish GTFS Validator'

on:
  workflow_dispatch:
  push:
    branches:
      - production
    paths:
      - "ts-wrapper/**/*"
      - "validator/**/*"
      - '!bin/**/*'

permissions:
  contents: write

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  version-number:
    name: 'Version Number'
    runs-on: ubuntu-latest
    steps:
      - id: generate-version-number
        run: |
          version="$(date +%Y%m%d).$(date +%H%M).$(date +%S)"
          echo "Generated version: $version"
          echo "version_number=$version" >> "$GITHUB_OUTPUT"
    outputs:
      version_number: ${{ steps.generate-version-number.outputs.version_number }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  ts-wrapper:
    name: 'Publish TS Wrapper'
    needs: version-number
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: tmlmobilidade/core/.github/actions/setup-node@production
        with:
          node-version: 20
          directory: ts-wrapper
          with-turbo-cache: false

      - name: Build package
        working-directory: ts-wrapper
        run: npm run build

      - name: Bump package version
        working-directory: ts-wrapper
        run: npm version --no-git-tag-version ${{ needs.version-number.outputs.version_number }}

      - name: Publish package to NPM
        working-directory: ts-wrapper
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  release-validator:
    name: Release Validator Binaries
    needs: version-number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Binaries
        shell: bash
        run: sh compile.sh

      - name: Commit Binaries to Releases
        uses: EndBug/add-and-commit@v9
        with:
          add: 'bin/*'
          message: 'chore: build validator binaries'
      