name: 'Publish GTFS Validator to npm'

on:
  workflow_dispatch:
  push:
    branches:
      - production
    paths:
      - 'ts-wrapper/**/*'
      - '.github/workflows/publish-wrapper.yml'

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish:
    name: 'Publish package'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: tmlmobilidade/core/.github/actions/setup-node@production
        with:
          node-version: 20

      - name: Build package
        working-directory: ts-wrapper
        run: npm run build

      - name: Bump package version
        working-directory: ts-wrapper
        run: npx @helperkits/bumper bump

      - name: Publish package to NPM
        working-directory: ts-wrapper
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}